---
# Install InfluxDB on Ubuntu
- name: Add InfluxDB repository
  apt_repository:
    repo: "{{ influx_repo.Ubuntu }}"
    state: present

- name: Install InfluxDB
  apt:
    name: influxdb
    state: present
    update_cache: yes

- name: Ensure InfluxDB is started and enabled
  service:
    name: influxdb
    state: started
    enabled: yes
