---
# Install InfluxDB on EL
- name: Add InfluxDB repository
  yum_repository:
    name: influxdb
    description: InfluxDB Repository
    baseurl: "{{ influx_repo.RedHat }}"
    gpgcheck: no
    enabled: yes

- name: Install InfluxDB2
  dnf:
    name:
      - influxdb2
      - influxdb2-cli
    state: present

- name: Ensure InfluxDB is started and enabled
  service:
    name: influxdb
    state: started
    enabled: yes
