---
# tasks file for influxDB


# Options: install, setup, resources, restore, all

- name: Create Storage directory
  ansible.builtin.file:
    path: "{{ influx_storage.path }}"
    state: directory
    owner: "{{ influx_storage.user }}"
    group: "{{ influx_storage.group }}"
    mode: "{{ influx_storage.mode }}"
  when: '"install" in influxdb_action or "all" in influxdb_action'

- name: Run installation tasks if requested
  ansible.builtin.include_tasks: "install_on_{{ ansible_os_family }}.yml"
  when: '"install" in influxdb_action or "all" in influxdb_action'

- name: Initial InfluxDB Setup
  ansible.builtin.include_tasks: setup.yml
  when: '"setup" in influxdb_action or "all" in influxdb_action'

- name: Add resources like buckets and tokens if requested
  ansible.builtin.include_tasks: resources.yml
  when: '"resources" in influxdb_action or "all" in influxdb_action'

