---
# tasks file for influxDB


# Optionen: install, setup, resources, restore, all

- name: Run installation tasks if requested
  ansible.builtin.include_tasks: "install_on_{{ ansible_os_family }}.yml"
  when: '"install" in influxdb_action or "all" in influxdb_action'

- name: Initial InfluxDB Setup
  ansible.builtin.include_tasks: setup.yml
  when: '"setup" in influxdb_action or "all" in influxdb_action'

- name: Add resources like buckets and tokens if requested
  ansible.builtin.include_tasks: resources.yml
  when: '"resources" in influxdb_action or "all" in influxdb_action'

