influxdb:
  vars:
    vault_secret: "vault_secret.txt"
    vault_file: "group_vars/all/vault.yml"
  hosts:
    rocky9-tls-sslcert:
      influx_tls_mode: system_sslcert
    rocky9-tls-acl:
      influx_tls_mode: system_acl
    rocky9-tls-influxcopy:
      influx_tls_mode: influx_copy
      influx_tls_ca_mode: ca_copy
    rocky9-no-tls:
      influx_tls_mode: no_tls

